### ISSUE TITLE
word suggestion being killed by phrase confidence

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.js#15]
After typing "The Word was" and having a threshold of 0.2, I should see "with God", but I don't because the period has a 0.17 confidence and the confidence of the last phrase is thus 0.17.  This filters out the words "with God," which makes sense in terms of what machine.js is doing, but not in terms of what a reasonable user would expect.
  The fix should be simple - if the phrase confidence is too small, check individual words and add them if they have a high enough confidence.

```
{
    "sourceSegmentLength": 6,
    "targetSegment": [
        "The",
        "Word",
        "was",
        "with",
        "God",
        "."
    ],
    "wordConfidences": [
        0.8474949,
        0.5266232,
        0.844647,
        0.8454712,
        0.88425213,
        0.1722885
    ],
    "phrases": [
        {
            "sourceSegmentRange": {
                "start": 0,
                "end": 2
            },
            "targetSegmentCut": 2,
            "confidence": 0.5266232
        },
        {
            "sourceSegmentRange": {
                "start": 2,
                "end": 3
            },
            "targetSegmentCut": 3,
            "confidence": 0.844647
        },
        {
            "sourceSegmentRange": {
                "start": 3,
                "end": 6
            },
            "targetSegmentCut": 6,
            "confidence": 0.1722885
        }
    ]
}
```

The relevant code portion that filters on phrase confidence: https://github.com/sillsdev/machine.js/blob/60b552c90d2bcafeef40842afb70ed92796002da/src/translation/phrase-translation-suggester.ts#L47

**Comment by ddaspit** [comment]
This has been fixed on master.
